name: Disable Deployments
on: deployment
permissions:
  deployments: write
jobs:
  disable:
    runs-on: ubuntu-latest
    steps:
      - name: Mark deployment as inactive
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/deployments/${{ github.event.deployment.id }}/statuses \
            -f state='failure'
        env:
          GH_TOKEN: ${{ github.token }}
